---
title: "Smiling your way to happiness or misery? Experimental tests of competing perspectives"
shorttitle: "Smiling and happiness"

format: html

author:
  - name: Nicholas A. Coles
    affiliations:
      - id: ufl
        name: University of Florida
        department: Department of Psychology
        address: 945 Center Dr, Gainesville, FL 32611
    email: ncoles@ufl.edu
    corresponding: true
  - name: Annabel V. Dang
    affiliations:
      - id: ufl
        name: University of Florida
        department: Department of Psychology
        address: 945 Center Dr, Gainesville, FL 32611
  - name: Joao Francisco Goes Braga Takayanagi
    affiliations:
      - id: ufl
        name: University of Florida
        department: Department of Psychology
        address: 945 Center Dr, Gainesville, FL 32611

abstract: |
Researchers and lay people alike have long been interested in whether people can make themselves feel happier if they simply fake a smile. Thus far, two largely disconnected research communities have provided seemingly competing answers to this question, with (a) emotion embodiment researchers observing positive causal links in experimental contexts, and (b) emotion labor researchers observing negative associations in real-world work contexts. In the present work, we conduct a pre-registered conceptual extension of the largest experimental demonstration of the positive effects of posed smiles on mood, focusing on three factors that may explain why such effects fail to generalize to real-world work contexts. More specifically, we test whether posed smiles fail to improve mood (1) in negative contexts, (2) when performed repeatedly, and/or (3) when performed to avoid punishment.

keywords:
  - emotion
  - emotion embodiment
  - emotion regulation
  - emotion labor
  - facial feedback
  - happiness

bibliography: r-references.bib

execute:
  echo: false
  warning: false
  message: false

editor_options:
  chunk_output_type: console
---

```{r}
#| label: setup
#| include: false
library(papaja)
```

# Introduction

"You'll find that life is still worthwhile, if you just smile" – Nat King Cole (1954)

“Pretending to be happy is almost like being happy. Until you remember that you’re only pretending. Then you’re sad. Really sad.” – Brittainy C. Cherry (2014)

Researchers, artists, and lay people alike have long wondered if people can make themselves feel happier if they simply fake a smile [@coles2019meta]. In addition to its allure as a cheap and scalable intervention for promoting happiness, such an idea connects to fundamental questions about the nature of emotion. For over a century, emotion embodiment researchers have posited that peripheral nervous system activity causally shapes emotion-related processes, including the subjective experience of emotion itself [@barrett2017theory; @cacioppo1992emotion; @damasio2013nature; @feldman2024neurobiology; @niedenthal2007embodying; @james1894physical; @james1948emotion; @scherer2019emotion; @tomkins1962affect; @wood2016fashioning]. To evaluate such possibilities, many researchers have conducted experiments with an easy-to-manipulate component of the peripheral nervous system: facial musculature. For example, in a study ostensibly about how muscle movements influence galvanic skin response, Coles, Gaertner, Frohlich, Larsen, and Basnight-Brown (Study 1, 2023) found that participants reported higher levels of happiness immediately after completing muscle movement trials that configured their face into a smile vs. scowl. Similar patterns have been observed in (1) multiple pre-registered replications (Baker, Van der Donck, Boets, & Korb, 2025; Coles et al., 2023; Noah, Schul, & Mayo, 2018; but see Wagenmakers et al., 2016), (2) a pre-registered meta-analysis of nearly 50 years of research (Coles, Larsen, & Lench, 2019), and (3) a large-scale adversarial collaboration conducted across 19 countries (Coles et al., 2022).

The emotion embodiment literature provides both a theoretical and empirical rationale for suggesting that people can make themselves feel happier if they “just smile” (Cole, 1954). However, if true, it is remarkable that people are generally *least happy* in jobs that notoriously require such behaviors, such as food and retail services (Smith, 2007). In actuality, researcherswho study these contexts often describe the negative effects of forcing one’s emotional expression to match the demands of a job (Hochschild, 1979)*.* Emotion labor researchers often describe posed smiles as “surface acting”, an act of feigning required emotional displays without changing internal states, which is often (imperfectly) likened to the notion of “expressive suppression” from research on basic emotion regulation strategies (e.g., Gross, 1998). Relative to strategies that involve re-interpreting negative thoughts (i.e., cognitive reappraisal) to genuinely feel and express required emotions, expressive suppression strategies are generally characterized as inferior (Webb, Miles, & Sheeran, 2012), counterproductive (Fernandes & Tone, 2021), and regulatorily costly in terms of decreases in well-being (Dryman & Heimberg, 2018; Hu et al., 2014; Yu, Haase, & Chang, 2023), social outcomes (Chervonsky & Hunt, 2017), and cognitive performance (Roche & Arnold, 2018; Zhu, Jiang, Wang, Liu, & Luo, 2021). Combined, this provides emotion labor researchers with both a theoretical and empirical rationale for warning against “pretending to be happy” (Cherry, 2024).

When two scientific perspectives compete, it is not uncommon for one camp to fail to recognize each other’s epistemic standards or legitimacy (Galison, 1997). In the context of smiling and happiness, some researchers may be tempted to dismiss the emotion labor perspective altogether due to internal validity concerns. For context, emotion labor researchers have documented a large number of negative correlations between smiling and indicators of happiness, often in real-world work contexts (Boemo, Nieto, Vazquez, & Sanchez-Lopez, 2022; Fernandes & Tone, 2021; Hülsheger & Schewe, 2011; Visted, Vøllestad, Nielsen, & Schanche, 2018). However, there are many confounds to consider. For example, negative correlations may be “due to the stressful situation that triggers negative emotions” requiring people to regulate their emotion expressions (Zapf et al., 2021, p. 165) – not the actual act of posing a smile. This could also potentially explain why researchers in a different theoretical tradition, emotion embodiment, observe positive effects of posed smiles: they overwhelmingly rely on experimental methods that manipulate smiling while controlling for potential confounding variables (e.g., the emotional nature of the situation; Coles et al., 2019).

Conversely, some researchers may be tempted to dismiss the emotion embodiment perspective over concerns about the ecological validity of their experimental settings. Experiments often bear little resemblance to real-world work conditions where people pose smiles – i.e., the setting where such acts tend to be linked with negative emotional outcomes. For example, consider the largest experimental demonstration of the effects of posed smiles on happiness (Coles et al., 2022). Participants were led to believe the study was focused on multi-tasking and were asked to complete a variety of movements (e.g., tapping their leg). For one of those movements, participants were asked to configure their face into a smile by following muscle-by-muscle movement instructions. Participants did indeed report improved moods after posing smiles. However, it’s possible that such effects do not generalize beyond these sets of relatively artificial conditions (e.g., to real-world work contexts).

## Present Work

The present work is designed to evaluate why the effects of posed smiles are often observed as positive in emotion embodiment research but negative in emotion labor research. We considered multiple way that these contexts differ[\[1\]](#_ftn1), ultimately choosing three to focus our initial inquiry: (1) the emotional contexts in which participants pose smiles, (2) the number of times they pose the smile, and (3) whether non-compliance could lead to financial penalties.

### The Emotion Incongruence Hypothesis: Posed Smiles Do Not Improve Mood in Negative Contexts

First, we consider an *emotion incongruence hypothesis*. Emotion embodiment researchers often study the effects of posed expressions in a context that is either neutral or emotionally congruent with the posed expression (e.g., positive if posing smiles; Coles et al., 2019). Once again, consider the largest experimental demonstration of such effects (Coles et al., 2022). Half of participants posed smiles while essentially staring at a blank screen, and the other half posed smiles while looking at mildly pleasant photos. However, when extending similar paradigms to a stressful context – like being submerged in ice water – researchers have thus far failed that posed smiles improve mood (Kraft & Pressman, 2012; Luu, Acevedo, Pourmand, & Pressman, 2025; Pressman, Acevedo, Hammond, & Kraft-Feil, 2021). In addition to providing one explanation for discrepancies between the emotion embodiment and labor literatures, such results challenge popularized claims about the ability for facial movement manipulations to improve mood in everyday negative situations. This includes not only recommendations to “just smile”, but also the neuromuscular electrical stimulation of facial musculature associated with positive expressions (Efthimiou, Baker, Elsenaar, Mehu, & Korb, 2025; Efthimiou et al., 2024) or the use of Botox treatments to inhibit activation in facial musculature associated with negative expressions (Schulze et al., 2021; Wollmer, Magid, Kruger, & Finzi, 2022). (For critiques of such clinical translations, see Coles & Larsen, 2021; Coles, Larsen, Kuribayashi, & Kuelz, 2019.)

### ***The Repetition Hypothesis: Posed Smiles Do Not Improve Mood When Performed Repeatedly***

Second, we consider a *repetition hypothesis*. According to this hypothesis, posed smiles may improve mood when performed once or twice – e.g., in the context of a typical emotion embodiment experiment. However, such effects may disappear (and even reverse) when people pose smiles repeatedly – e.g., in the context of a typical workplace studied by emotion embodiment surveys. Practically, such a result would highlight the importance of posing smiles in moderation. For example, rather than requiring workers to feign happiness in every interaction, worker well-being may be maximized by only asking them to do so in their most difficult interactions.

### ***The Punishment Hypothesis: Posed Smiles Do Not Improve Mood When Performed to Avoid Punishment***

Third, we consider a *punishment hypothesis*: posed smiles can improve mood when performed relatively voluntarily in emotion embodiment research – but not when done under threat of punishment (e.g., reduced tips, docked performance evaluations, or job loss) in emotion labor research. More practically, such results directly connect to conversations about eradicating emotion display requirements at work altogether (Grandey, Rupp, & Brice, 2015). Such conversations often consider seemingly conflicting evidence from the emotion embodiment literature: that posed smiles can increase happiness in experimental contexts (e.g., Chandwani & Sharma, 2015; Choi & Kim, 2015). However, the punishment account potentially explains why these effects do not generalize to work settings: smiling isn’t mood boosting when performed to avoid punishment.

# Method

In the present work, we evaluate the emotion incongruence, repetition, and punishment accounts side-by-side. To do so, we will extend a paradigm used in the largest experimental demonstration of the mood-boosting effects of posed smiles (Coles et al., 2022) to include three experimentally-manipulated factors: (1) the emotional contexts in which participants pose smiles, (2) the number of times they pose the smile, and (3) whether non-compliance could lead to financial penalties.

The present study features a 2 (Face Movement: pose smile, express naturally) x 2 (Emotional Context: positive, negative) x 2 (Movement Repetitions: one time, ten times) x 2 (Punishment Threat: present, absent) design, with the first factor manipulated within-subjects. These manipulations are designed to evaluate boundary conditions of the mood-boosting effect of posed smiles – although they cannot necessarily explain *why* those conditions matter. For example, Punishment Threat may eliminate the mood-boosting effect of posed smiles because it shifts the perceived goal of the smile (to avoid financial penalty vs. appease an experimenter). But it may also eliminate the mood-boosting effect of posed smiles because it is intrinsically unpleasant. Our Registered Report focuses on identifying these boundary conditions with a pre-registered and pre-vetted design, sampling plan, and analysis strategy (<https://osf.io/2suyx/?view_only=8052e16be97d4bee8f93a6fa67b02893>).

## Participants

N = 1200 participants will be recruited from Prolific: an online platform where people complete studies in exchange for payment. (See *Power Simulation* for more information.) Workers on the platform will be eligible to participate if they (a) speak English, (b) have a functioning webcam, (c) have previously completed at least 5 studies, and (d) have at least 90% of their study submissions accepted. These latter two criteria help ensure that the quality of participants’ responses has been vetted by other researchers.

## Design

## Procedure

Participants will complete the online experiment via a browser-based platform, Gorilla Experiment Builder (Anwyl-Irvine, Massonnié, Flitton, Kirkham, & Evershed, 2020). To minimize the impact of demand characteristics (Coles, Wyatt, & Frank, 2025; Orne, 1962), participants will be told the study examines “how physical multi-tasking influences mathematical speed and accuracy”. For payment, participants will be told that they will receive up to \$6. However, half of participants will be informed that \$2 will be deducted if we do not find that they followed instructions satisfactorily during recorded segments of the study. This serves as our manipulation of Punishment Threat, but all participants will ultimately receive full compensation (\$6). Regardless of assigned condition, participants will be informed of recording and will confirm webcam functionality by submitting and confirming the playback of a short video through the survey program.

During the study, participants will complete four trials, all of which are conceptual replications of a large multi-lab adversarial test of facial feedback effects (Coles et al., 2022). The first and last trial are sham tasks designed to corroborate the cover story. E.g., in the first trial, participants will be asked to “place your left hand behind your head and blink your eyes once per second for 5 seconds”. In the last trial, they will be asked to “Tap your left leg with your right-hand index finger once per second for 5 seconds.”

More critically, in the second and third trials, participants will be instructed to pose smiles or express themselves normally for 5 seconds. This serves as our manipulation of Face Movement. Participants will be shown four images of actors trained to display prototypical expressions of happiness. These images were originally compiled from the Extended Cohn-Kanade Dataset (Lucey et al., 2010) and arranged in a single 2x2 image matrix (Coles et al., 2022). Participants will be asked to either (a) adopt the pictured expression, or (b) not attempt to control their face movements. Importantly, having participants view the same image matrix in both trials helps eliminate the potentially confounding effect that images of smiling people may have on emotional experience. Limiting the pose to 5 seconds helps ensure a similar duration as authentic emotional expressions (Ekman, 2003).

During the two face movement trials, participants will encounter images previously validated to elicit either a positive or negative mood (Coles, 2020). This serves as our manipulation of Emotional Context. For positive contexts, participants will view images of flowers, kittens, and rainbows, arranged in a single 1 x 3 row. For negative contexts, they will view images of inconsiderately parked vehicles, acts of theft, and animal maltreatment (also arranged in a single row). Images will be displayed alongside an on-screen timer while participants complete the face movement task. While doing so, participants will be recorded through their webcam, which will be automatically toggled on and off by the survey program.

Half of participants will be randomly assigned to complete the face movement task once before proceeding to the next trial, which serves as a conceptual replication of Coles et al. (2022). The other half of participants will be assigned to complete the task ten times. This serves as our manipulation of Repetition. Immediately after completing the face movement task (either once or ten times), participants will complete a modified Discrete Emotions Questionnaire, wherein they will report the extent to which they experienced a variety of emotions during the preceding trial (1 = Not at all, 7 = An extreme amount; Harmon-Jones, Bastian, & Harmon-Jones, 2016). Following Coles et al. (2023), we modified the questionnaire in three ways. First, to shorten the length, we limited ourselves to three items per subscale. Second, we replaced the original anger items (anger, rage, mad, and pissed off) with more moderate options (e.g., irritation). Third, we limited ourselves to three emotion subscales: happiness (three averaged items: happiness, satisfaction, and enjoyment), anger (irritation, aggravation, and annoyance), and fear (alarmed, scared, fear). Multiple emotion subscales were used to obscure our interest in any specific emotional state.

The key outcome-of-interest is self-reported happiness. However, we will also explore effects on two other outcomes frequently discussed in the emotion labor literature: well-being and burnout. After self-reporting their emotions, participants will complete measures of satisfaction with life (e.g., “In most ways my life is close to my ideal”; 1 = Strongly Disagree, 7 = Strongly Agree; Diener, Emmons, Larsen, & Griffin; 1985) and burnout (e.g., “To what extent to you feel hopeless”; 1 = Not at all, 7 = An extreme amount; Malach-Pines, 2005). Afterwards, participants will complete a simple filler math problem (e.g., 2+ 2 = ?). This is done to both (a) corroborate the cover story and (b) evaluate whether participants are paying attention.

After completing all trials, participants will self-report their age, gender (Male, Female, Nonbinary; Garbarski, Dykema, Yonker, Bae, & Rosenfeld, 2025), and ethnicity (Revesz, 2024). Afterwards, participants will be asked two questions in a funnel debriefing. First, participants will simply be asked what they believe was the purpose of this study. Second, they will be informed that “There are details about the purpose of this study that we have not yet told you about” and asked to guess those details. Afterwards, participants will be fully debriefed.

After the study is complete, we will evaluate how well participants completed the face movement tasks. To do so, we will use a commercially available emotion expression recognition model, Hume AI (https://www.hume.ai/). Like other emotion expression recognition models, Hume AI uses computer vision to track facial landmarks (e.g., lips) associated with emotion expression (e.g., smiling) in each frame of a user-uploaded video. These features are passed through a pre-trained deep neural network to predict observer ratings of emotion (Cowen et al., 2021). To be clear, such models can fail to accurately infer peoples’ subjective emotional experiences in complex and/or real-world scenarios (Cross, Acevedo, & Hunter, 2023). However, in relatively simple experimental contexts like ours, such models have been successfully deployed to identify non-smiling participants in an efficient and scalable manner (Coles, 2020; Coles et al., 2022). In the present work, we will use Hume AI to generate moment-to-moment estimates of smiling-related activity using Facial Action Coding System classifications (Ekman & Friesen, 1978). We will focus on Action Unit 12 in particular (measured on a 0 – 1 scale), which is associated with pulling the corner of the lips back towards the ear.

## Measures

# Results

As a reminder, our study deploys a 2 (Face Movement: pose smile, express naturally) x 2 (Emotional Context: positive, negative) x 2 (Movement Repetitions: one time, ten times) x 2 (Punishment threat: present, absent) design, with Face Movement manipulated within-subject.

The emotion incongruence, repetition, and punishment hypotheses all predict a two-way interaction with Face Movement – but differ in their proposed moderating factor. More specifically, the emotion incongruence hypothesis predicts a two-way interaction between Face Movement and Emotional Context, wherein there are only positive simple effects of Face Movement in positive contexts (Table 1). The repetition hypothesis predicts a two-way interaction between Face Movement and Movement Repetition, wherein Face Movement only has a positive simple effect when repeated once (Table 1). Last, the punishment hypothesis predicts a two-way interaction between Face Movement and Punishment, wherein there are only positive simple effects of Face Movement when there is no stated punishment for non-adherence (Table 1).

# Discussion

# References